{"name": "Проверка сообщения об ошибке при обновлении email пользователя без авторизации", "status": "passed", "steps": [{"name": "Отправка запроса", "status": "passed", "parameters": [{"name": "method", "value": "'PATCH'"}, {"name": "endpoint", "value": "'/auth/user'"}, {"name": "json", "value": "{'email': 'new_email@example.com'}"}], "start": 1737273839507, "stop": 1737273839649}], "start": 1737273839507, "stop": 1737273839649, "uuid": "043b5c94-8a87-42f1-81a5-d58a1e6f3ccb", "historyId": "f9e7c9358858022607cc3fedb3e426a7", "testCaseId": "f9e7c9358858022607cc3fedb3e426a7", "fullName": "tests.test_update_user_data.TestUserUpdate#test_update_user_without_auth_email_error_message", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user_data"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "SergeiBazhenov"}, {"name": "thread", "value": "12572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user_data"}]}