{"name": "Проверка статус-кода при получении заказов неавторизованным пользователем", "status": "passed", "start": 1737273833810, "stop": 1737273833946, "uuid": "eafe7506-b95f-417e-bdb0-a9b991170763", "historyId": "05aed6c45034e4c4ffd15cd6290be512", "testCaseId": "05aed6c45034e4c4ffd15cd6290be512", "fullName": "tests.test_get_orders.TestGetUserOrders#test_get_orders_unauthorized_user_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "SergeiBazhenov"}, {"name": "thread", "value": "12572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}